FROM node:22-alpine as build

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

RUN npm ci

COPY --chown=node:node . .

RUN npm run build

# Production Stage
# FROM node:22-alpine AS production

# WORKDIR /usr/src/app

# COPY --from=build /usr/src/app/dist ./dist
# COPY --from=build /usr/src/app/node_modules ./node_modules
# COPY package*.json ./

CMD ["npm", "run", "start:prod"]