# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: app
#     image: app:latest
#     restart: always
#     ports:
#       - '3000:3000'
#     environment:
#       # добавьте переменные окружения, если нужно (.env файл или прямо сюда)
#       - NODE_ENV=production
#     volumes:
#       - .:/app # монтируем исходники для hot-reload (при разработке)
#       - /app/node_modules # избегаем перезаписи node_modules из хоста
#     command: npm run start:dev # или используйте команду для разработки с hot reload
#     # develop:
#     #   watch:
#     #     - action: sync
#     #       path: ./src
#     #       target: /app/src

#   postgres:
#     container_name: postgres
#     # image: maxlisyanskiy/postgres:latest
#     # docker build -t maxlisyanskiy/postgres:latest .
#     # docker push maxlisyanskiy/postgres:latest
#     # docker pull maxlisyanskiy/postgres:latest
#     image: postgres:latest
#     environment:
#       - POSTGRES_USER=${PG_USER}
#       - POSTGRES_PASSWORD=${PG_PASSWORD}
#       # - PGDATA=/data/postgres
#     ports:
#       - '${PG_PORT:-5432}:5432'
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#       - postgres_logs:/var/log/postgresql
#       # - postgres:/var/www/nest_test/docker-volumes/postgres
#     networks:
#       - nestjs_network
#     restart: unless-stopped

# networks:
#   nestjs_network:
#     driver: bridge

# volumes:
#   postgres_data:
#   postgres_logs:
#   nest_test_pgadmin:

# services:
#   db:
#     image: postgres
#     restart: always
#     environment:
#       - POSTGRES_PASSWORD=postgres
#     container_name: postgres
#     volumes:
#       - ./pgdata:/var/lib/postgresql/data
#     ports:
#       - '5432:5432'

#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: app
#     environment:
#       - PORT=${PORT}
#     ports:
#       - '${PORT}:${PORT}'
#     depends_on:
#       - db
#     volumes:
#       - ./src:/app/src

#   pgadmin:
#     image: dpage/pgadmin4
#     restart: always
#     container_name: nest-pgadmin4
#     environment:
#       - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#       - PGADMIN_DEFAULT_PASSWORD=pgadmin4
#     ports:
#       - '5050:80'
#     depends_on:
#       - db

services:
  # Database service (PostgreSQL)
  db:
    image: postgres:17-alpine
    container_name: nestjs-db
    restart: always
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    ports:
      - '${PG_PORT}:${PG_PORT}'
    networks:
      - custom_network
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
      - ./volumes/postgres_logs:/var/log/postgresql

  # pgAdmin service (PostgreSQL)
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: nestjs-pgadmin4
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@example.com
  #     - PGADMIN_DEFAULT_PASSWORD=admin
  #   ports:
  #     - '5050:80'
  #   depends_on:
  #     - db
  #   networks:
  #     - custom_network
  #   volumes:
  #     - ./volumes/pgadmin:/var/lib/pgadmin
  #   profiles:
  #     - dev

  # Development service
  app-dev:
    container_name: nestjs-app-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: on-failure
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    # volumes:
    #   - .:/usr/src/app
    #   - /usr/src/app/node_modules
    networks:
      - custom_network
    depends_on:
      - db
    profiles:
      - dev
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

  # Prodution service
  app-prod:
    container_name: nestjs-app-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    networks:
      - custom_network
    depends_on:
      - db
    profiles:
      - prod

networks:
  custom_network:
    driver: bridge
